Module _4_08
    Sub main()

        Dim paises As New Hashtable

        Dim pais As String

        paises.Add("AR", "Argentina")
        paises.Add("BR", "Brasil")
        paises.Add("CH", "Chile")
        paises.Add("PE", "Perú")
        paises.Add("UR", "Uruguay")

        Console.Write("Ingresar un dominio de un país para ver si se encuentra")
        pais = Console.ReadLine



    End Sub
End Module
